---
title: "Studying JavaScript Promises"
date: 2018-03-18T16:37:50+03:00 
draft: false
description: ""
tags:
categories: js
type: post
url:
author: "Mert Nuhoglu"
output: html_document
blog: mertnuhoglu.com
resource_files:
- ex/study_js_promises_ex01/package.json
- ex/study_js_promises_ex01/script01.js
- ex/study_js_promises_ex01/script02.js
- ex/study_js_promises_ex01/script03.js
- ex/study_js_promises_ex01/script04.js
- ex/study_js_promises_ex01/script05.js
- ex/study_js_promises_ex01/script06.js
- ex/study_js_promises_ex01/script07.js
- ex/study_js_promises_ex01/script08.js
path: ~/projects/study/js/study_js_promises.Rmd
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
</style>

## v01: Basic Example 01

Studying the tutorials given in https://egghead.io/lessons/javascript-promises-with-es6

Source code in https://github.com/mertnuhoglu/study/js/ex/study_js_promises_ex01/

``` {bash}
mkdir -p ex/study_js_promises_ex01
cd ex/study_js_promises_ex01
``` 

Edit `script01.js`

``` js
var d = new Promise((resolve, reject) => {
  if (true) {
    resolve('hello world');
  } else {
    reject('no bueno');
  }
});
d.then((data) => console.log('success : ', data));
d.catch((error) => console.log('error : ', error));
``` 

``` {bash}
node ex/study_js_promises_ex01/script01.js
``` 

Let's make `reject` be run:

Edit `script02.js`

``` js
...
  if (true) {
    resolve('hello world');
  } else {
    reject('no bueno');
  }
``` 

``` {bash}
node ex/study_js_promises_ex01/script02.js
``` 

## v03: Asynchronous behaviour using Promises

Edit `script03.js`

``` js
...
  setTimeout(() => {
    if (true) {
      resolve('hello world');
    } else {
      reject('no bueno');
    }
  }, 1000);
``` 

``` {bash}
node ex/study_js_promises_ex01/script03.js
``` 

## v04: Style: instead of `catch` append a new lambda parameter to `then`

``` js
...
d.then(
  (data) => console.log('success : ', data)
  , (error) => console.log('error : ', error)
);
``` 

``` {bash}
node ex/study_js_promises_ex01/script04.js
``` 

## v05: Style: `catch` `then` methods can be chained

``` js
...
d.then( (data) => console.log('success : ', data) )
  .catch( (error) => console.log('error : ', error) );
);
``` 

``` {bash}
node ex/study_js_promises_ex01/script05.js
``` 

Multiple `then` can be chained too:

``` js
...
d.then( (data) => console.log('success : ', data) )
  .then( (data) => console.log('success 2 : ', data) )
  .catch( (error) => console.log('error : ', error) );
);
``` 

``` {bash}
node ex/study_js_promises_ex01/script06.js
``` 

But note the output: `success 2 :  undefined`. This is because the second chain gets its input data from the previous chain's return value.

``` js
...
d.then( (data) => {console.log('success : ', data); return 'foo';} )
  .then( (data) => console.log('success 2 : ', data) )
);
``` 

``` {bash}
node ex/study_js_promises_ex01/script07.js
``` 

## v08: Any Exception inside Promise triggers `catch` method

It doesn't matter where the exception is thrown. It will trigger `catch` method.

``` js
var d = new Promise((resolve, reject) => {
  throw new Error('error here');
  ...
``` 

``` {bash}
node ex/study_js_promises_ex01/script08.js
``` 

